### ISSUE TITLE
如果dnsResolve返回的是IPV6地址你这样做会出错的吧

### ISSUE THREAD

**Issue by sharuijinfriend** [iBug/pac#1]
我仔细看了你写的pac，感觉仅仅考虑了返回是v4地址的情况，碰到返回v6地址应该是会出错的吧

**Comment by iBug** [comment]
是的，这个问题发现得好。

我编的这几个 PAC 文件是设计给代理 (主要是 Shadowsocks) 使用的。以目前的受众 (基于 IPv4 的 Shadowsocks 用户)，这个依赖是没问题的，IPv4 代理提供的这些效用函数只会返回 IPv4 结果，所以暂时没有出错的可能。

另外一个重要原因是，我暂时没有任何关于 IPv6 分配信息的资源，所以这个 PAC 暂时没法改写 IPv6。如果一定要处理，也只能在 `dnsResolve()` 返回 IPv6 地址时特殊处理。

**Comment by sharuijinfriend** [comment]
嗯嗯，我暂时先按照返回的结果如果不符合ipv4的格式（也就是ipv6地址）就全部走代理，不过这样的话像六维空间这样的资源站就上不去了。可能还是需要更复杂的规则去处理这种情况，但是我目前也没找到很好的国内ipv6地址列表。

**Comment by redstoneleo** [comment]
> 如果不符合ipv4的格式（也就是ipv6地址）就全部走代理
要怎么改代码才能这样子？请指教！

**Comment by iBug** [comment]
一个简单的办法是直接判断 `host` 里面有没有冒号，有的话就肯定是 IPv6 地址了，因为 `host` 不会带端口号，所以冒号不会有其他的来源。

**Comment by redstoneleo** [comment]
那应该是在这一行下面开始判断了
https://github.com/iBug/pac/blob/master/code.js#L41
我改成这样，不起作用啊
```
function FindProxyForURL(url, host) {
  if (!isResolvable(host)) {
    return proxy;
  }
  var remote = dnsResolve(host);
   if (remote.indexOf(':')!=-1){
  return proxy;
}
 else if (isLan(remote) || isChina(remote)) {
    return direct;
  }
  return proxy;
}
```
请问什么原因？
