### ISSUE TITLE
gstatic.com这个网址无法正常代理

### ISSUE THREAD

**Issue by Yu4n** [iBug/pac#10]
搜索 define "某个单词" 时无法听音频, 必须开启全局代理才行.

**Comment by Yu4n** [comment]
Request URL: https://ssl.gstatic.com/dictionary/static/sounds/20180430/awareness--_us_1.mp3
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept-Encoding: identity;q=1, *;q=0
DNT: 1
Range: bytes=0-
Referer: https://www.google.com/search?q=def+function&oq=def+function&aqs=chrome..69i57j0l6.3028j0j7&sourceid=chrome&ie=UTF-8
Sec-Fetch-Dest: audio
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48

**Comment by iBug** [comment]
检查一下 DNS 结果，然后试试两个不同的 IP 地址列表。这个项目是根据域名解析出的 IP 地址来判断是否要走代理的。

**Comment by Yu4n** [comment]
> 检查一下 DNS 结果，然后试试两个不同的 IP 地址列表。这个项目是根据域名解析出的 IP 地址来判断是否要走代理的。

查出来了  DNS解析错了。

**Comment by Yu4n** [comment]
还有一个问题，gfwlist上也有这个域名但同样不能加载。按理说应该都是远程dns解析的，为什么修改本地dns会有效呢？中间哪一步走了运营商的dns？

**Comment by iBug** [comment]
gfwlist 是直接按域名黑白名单的，不经过 DNS，和本项目不一样
