### ISSUE TITLE
请教代码相关问题

### ISSUE THREAD

**Issue by redstoneleo** [iBug/pac#11]
1. belongsToSubnet里用了二分查找的算法，能否考虑使用[Set.prototype.has()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has)来代替，记得书上说has涉及到的是hash算法，O(1)之类的，去考虑一下吧
2. `ip = 0x1000000 * Number(ip[0]) + 0x10000 * Number(ip[1]) +0x100 * Number(ip[2]) + Number(ip[3]);`能否加点注释解释下这是什么操作，什么原理，谢谢！

**Comment by iBug** [comment]
1. 非常感谢，`Set()` 我之前没了解过，<s>回头可以尝试一下。</s>

   问题好像出在这个地方，我不是要匹配等于，而是要找到 `x[n] <= ip < x[n+1]` 的这样一个 `n`，然后进行更多运算。Set 在这里似乎没什么意义。

   具体的逻辑是，我希望判断是否存在一个 `[net, mask]` 二元组使得 `(ip & mask) == net`，由此来判断给定的 IP 地址是否属于某个子网段。应该有能用上 Set 的办法，但是我估计会比较麻烦。

2. 这段代码是这样的：

   <https://github.com/iBug/pac/blob/e8e027b84d633d88b481e7b2f2188459b6031488/code.js#L5-L7>

   传进来的 `host` 是一个 IPv4 地址，`split` 之后的结果类似这样 `["127", "0", "0", "1"]`，要将四个字符串转换为数字然后按大端序拼成一个 32 位整数用于二分查找。

**Comment by redstoneleo** [comment]
那么第二个问题里belongsToSubnet(host, list)提到的host应该改为ip才符合语义啊，害惨我和FindProxyForURL(url, host)里的host混淆了~~~

**Comment by redstoneleo** [comment]
这个网址在这种pac下就访问不了
https://www.google.com/search?newwindow=1&sxsrf=ACYBGNQNglqShAaCEtTTXGjLzDdkZTQIBA%3A1576660831283&ei=X-_5XbnwENXj-AbIlL2YDw&q=chrome+extension+Not+allowed+to+load+local+resource%3A+chrome%3A%2F%2Fbookmarks%2F&oq=chrome+extension+Not+allowed+to+load+local+resource%3A+chrome%3A%2F%2Fbookmarks%2F&gs_l=psy-ab.3...928331.945565..946021...0.0..0.469.920.2-2j0j1......0....1j2..gws-wiz.......0i30j0i333j0i8i30.DIkZYuZWIG8&ved=0ahUKEwj5m56m777mAhXVMd4KHUhKD_MQ4dUDCAs&uact=5

**Comment by iBug** [comment]
检查一下你的 DNS 有没有问题

**Comment by redstoneleo** [comment]
dns没问题，Facebook，YouTube，谷歌香港都可以，https://www.google.com/ 就是不行

**Comment by junmin** [comment]
@redstoneleo 我也在调试，打开google.com没有问题

**Comment by iBug** [comment]
看看 `www.google.com` 的解析结果。正常情况下这个域名的解析结果都不在 china ip list 里，我这边没发现任何问题

**Comment by redstoneleo** [comment]
```
C:\Users\i>ping www.google.com

正在 Ping www.google.com [2001::1f0d:4917] 具有 32 字节的数据:
请求超时。
请求超时。
一般故障。
一般故障。

2001::1f0d:4917 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\i>
```
是ipv6造成的吗？之前听说本项目只支持ipv4

**Comment by iBug** [comment]
#1

**Comment by Zhwt** [comment]
要考虑优化的话是否可以参考一下 SO 上的这一篇 [JavaScript: Is IP In One Of These Subnets?](https://stackoverflow.com/a/503238/6642154), 使用位运算的方式计算 IP 所属网段
但感觉有个问题就是最后这个匹配可能不太好搞, 只是提供一种优化的思路

**Comment by iBug** [comment]
@Zhwt 我现在用的就是位运算：

<https://github.com/iBug/pac/blob/854289a674578d096f60241804f5893a3fa17523/code.js#L21-L23>

那个 SO 答案我看过了，没啥有价值的，都是匹配一个子网，而不是匹配一堆子网的。

（我把我的代码当作一个答案提交上去了：<https://stackoverflow.com/a/60255739/5958455>）
