### ISSUE TITLE
V2rayN无法正常工作，主要是百度网站无法走直连

### ISSUE THREAD

**Issue by timeneverdie** [iBug/pac#12]
配置方法：
去ibugone网站生成并下载pac.txt，手动覆盖到V2rayN的根目录，在GUI里重启V2rayN服务。V2rayN设置为启用PAC模式，并未使用软件自带更新PAC功能。

Bug表现：
生成PAC时候，如果勾选4.1.9兼容模式，则全部走代理服务器；如果不勾选4.1.9兼容模式，则全部走直连，无法通过PAC实现分流。

更新1：
经过测试，发现PAC在大部分网站是正常工作的，唯独百度不行，因为一开始以百度作为判断依据，所以出现了偏差。在其他大陆网站都直连的情况下，唯独百度还是走代理，实在是奇怪。怀疑是百度在日本有业务，Google的DNS便将我这个日本IP优先连入百度。

更新2：
更换美国节点后，百度搜索”IP“依然识别为美国，而其他大陆网站识别正常，都是直连。

**Comment by iBug** [comment]
估计是 DNS 问题，我这边可能管不了，和 #8 一起处理吧。

**Comment by timeneverdie** [comment]
> 估计是 DNS 问题，我这边可能管不了，和 #8 一起处理吧。

我刚刚在v2rayN的设置里，找到”Core：路由设置“，然后点开”预设规则“，设置为”绕过局域网和大陆地址“，就一切正常了（代理模式设置为PAC模式），这是什么原理？是不是这个选项的优先级比pac.txt还高？使用内建规则所以无视pac.txt文件？

**Comment by iBug** [comment]
据我了解，v2rayN 是两级分流。Core 决定流量是否经过梯子，而 PAC 只是决定流量是否经过 Core。

https://github.com/2dust/v2rayN/issues/83#issuecomment-569159270

**Comment by iBug** [comment]
另外 v2rayN 的 PAC 格式似乎不太一样，如果你能提供一个 v2 的 PAC 文件做参考我或许可以看看适配一下
