### ISSUE TITLE
关于v2rayN客户端的PAC文件

### ISSUE THREAD

**Issue by qianxundai** [iBug/pac#17]
我发现从这里下载下来的pac文件改名后是无法直接使用的
但是把第5行
var proxy = __PROXY__;
改为
var proxy = "__PROXY__";
加个双引号就可以使用了

**Comment by iChoix** [comment]
> 我发现从这里下载下来的pac文件改名后是无法直接使用的 但是把第5行 var proxy = **PROXY**; 改为 var proxy = "**PROXY**"; 加个双引号就可以使用了

![image](https://user-images.githubusercontent.com/6520601/160854588-848fc299-0387-4134-b8ff-e78d2f79ef85.png)
请问是改成这样即可吗？
