### ISSUE TITLE
你好，请问怎么更新这个ip地址，因为我看网站上ip地址段会变化，将来可能需要更新

### ISSUE THREAD

**Issue by 380cc** [iBug/pac#2]
你好，请问怎么更新这个ip地址，因为我看网站上ip地址段会变化，将来可能需要更新
ip地址部分倒是可以通过网上在线的工具批量转换,但子网掩码部分怎么批量转换生成呢？
请教 我也不懂什么派森开发。

**Comment by iBug** [comment]
前排通知 3：[Releases](https://github.com/iBug/pac/releases/latest) 每周六晚上 8 点（北京时间）自动冒出新的 Release，包含从数据源新生成的 pac 脚本。

<s>前排通知 2：[`dist` 分支](https://github.com/iBug/pac/tree/dist)每周六晚上 8 点（北京时间）自动冒出新的 pac 脚本。</s> **Deprecated**

从开源项目的内容完整性角度考虑，我现在觉得另外搞个生成器放在自己个人网站上不太好，把代码和资源拆太散了。另一个问题是目前已有的两个数据源更新频率都很低，弄一个网页版实时生成的工具有点多余，使用 GitHub Actions 每周自动更新已经足够了。

<s>前排通知：我重新做了一个[网页版的生成器](https://ibugone.com/project/pac-generator)，取代本仓库。可以直接用浏览器打开，直接获取最新版的 IP 地址列表，生成 PAC 并下载到本地，方便又快捷。</s>

<s>把更新过的IP地址段列表保存为 `ip_ranges.txt`，然后运行 Python 脚本就可以得到输出。

如果你需要自己更新 PAC 文件，更简单的办法是直接运行 `build.sh` (macOS 或 Linux)，运行完成得到 `out.pac` 就是直接可用的。</s>

**Comment by dNEryno** [comment]
phyton3 装了
2019-05-05 06:45:38 (281 KB/s) - ‘ip_ranges.txt’ saved [79680/79680]

./build.sh: line 13: python3: command not found
cat: code.js: No such file or directory


报错。。无法运行得到结果。。麻烦大佬看看呀

**Comment by ghost** [comment]
你好，我使用了你的PAC规则，效果很好，但推特打开有问题，按你楼上的操作更新了PAC文件后依然如此，请问你打开推特有这样的问题吗？

**Comment by iBug** [comment]
@auxf0rd 我这边没问题。你可以尝试在自己电脑上查一下 twitter.com 的 IP 地址，然后比较一下。有可能是 DNS 污染导致上不去。

**Comment by iBug** [comment]
我又更新了一些代码，请看[上面的回复](https://github.com/iBug/pac/issues/2#issuecomment-462220411)

**Comment by moneyyes** [comment]
感谢作者m(_ _)m
白名单式pac真的很好用
