### ISSUE TITLE
Preprocess not working

### ISSUE THREAD

**Issue by kingfisher77** [iBug/pac#21]
Hi, thank you for this code. It works with your example data but not with newly added subnets.

If i add this subnet the result is always false, also for the other ones. 

[0x58cd6368, 0x1e000000], // 88.205.99.104/30

What is wrong?

**Comment by iBug** [comment]
You need to insert extra subnet ranges to the correct place because the code uses binary search, which expects the IP range list to be sorted.

Also a subnet mask of 30 should be written as `0xFFFFFFFC` (30 leading ones with 2 trailing zeros).

**Comment by kingfisher77** [comment]
Now i understand where my flaw was. Thank you!
