### ISSUE TITLE
有个mono_pac的项目，里面有一些pac脚本的优化。

### ISSUE THREAD

**Issue by alongyou** [iBug/pac#28]
有个mono_pac的项目，里面有一些pac脚本的优化。方便把他的一些优化pac脚本的功能移植进来吗。
比如 ip地址表，用数字数组，和掩码数组分开。

**Comment by iBug** [comment]
这个项目我自己已经不再使用了，所以我也不会再继续开发维护了，欢迎自行 fork，做得好的话我可以加进 README 宣传一下
