### ISSUE TITLE
你好，怎么 更改bypass-lan-and-china.pac 翻墙回国呢？

### ISSUE THREAD

**Issue by pocupine** [iBug/pac#3]
你好，
我有小爱音箱，机顶盒，电脑之类的想一起wifi hotspot 翻墙回国，我家里有一个win服务器。
请问怎么更改bypass-lan-and-china.pac 翻墙回国呢？谢谢你。
Clement

**Comment by iBug** [comment]
生成（或获取）`out.pac` 之后，找到 `function FindProxyForURL`，把里面两个 `return` 行交换一下就行了，这样就变成了 IP 地址在大陆地址表中的时候走代理，不在表中的时候不走代理，正好和默认行为相反。

**Comment by pocupine** [comment]
谢谢
