### ISSUE TITLE
如何让脚本兼容支持shadowsocks-windows？

### ISSUE THREAD

**Issue by timeneverdie** [iBug/pac#4]
一直用这个pac：https://github.com/breakwa11/gfw_whitelist/raw/master/whiteiplist.pac

因为IP段长期不更新，一直在找新的pac。用了你的pac，发现无法连接外网，这是什么原因呢？我看整体上你的代码和breakwa11的差不多啊。breakwa11这个pac本身也是为ssr客户端开发的，但是可以完美兼容ss客户端。

**Comment by timeneverdie** [comment]
是这一行代码没有修改为代理地址的原因吗？
`var proxy = "__PROXY__";`

**Comment by iBug** [comment]
你可以尝试自己改一下，不过我就是 ss-win 的用户 (v4.1.7.1)，没觉得有任何问题

**Comment by timeneverdie** [comment]
> 你可以尝试自己改一下，不过我就是 ss-win 的用户 (v4.1.7.1)，没觉得有任何问题

PAC在线地址直接填入这个地址 https://github.com/iBug/pac/raw/master/bypass-lan-and-china.pac 就可以使用了吧？可是我真的用不起来啊。回头试试改下proxy的值是不是能生效。

**Comment by iBug** [comment]
我最初设计的用法倒不是让你直接填在线地址的，而是把内容复制下来，在 ss-win 里选”编辑本地 PAC“然后粘贴进去的。

**Comment by timeneverdie** [comment]
> 我最初设计的用法倒不是让你直接填在线地址的，而是把内容复制下来，在 ss-win 里选”编辑本地 PAC“然后粘贴进去的。

我把pac文件下载下来，重名为pac.txt，覆盖原来的pac.txt，就可以使用了。
在线pac有好处有坏处，好处是全自动更新，坏处是每次切换ss代理模式都要重新下载一次pac文件才能联网，而且不能更换ss本地端口。
现在综合体验下来还是本地pac好使，自己定期下载pac文件手动更新一下就行了，反正IP段变化不大。
最后再次感谢作者的开发。
