### ISSUE TITLE
无法正常下载

### ISSUE THREAD

**Issue by junmin** [iBug/pac#9]
网页生成器那里，按了生成之后有看到生成一些代码，但是按下载就没有反应，是不是有点问题？
我在mac os上使用 ShadowsocksX-NG客户端（1.9.4版本）, 请问兼容使用吗？

**Comment by iBug** [comment]
我这里功能正常，请问你用的什么浏览器？

兼容性不知道，我只在 Shadowsocks-Windows 上用过，其他平台请自己测试。

**Comment by junmin** [comment]
@iBug 

Google Chrome
Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by junmin** [comment]
@iBug 

safari, firefox 也试了一下，一样的问题，按下载没反应

**Comment by iBug** [comment]
我这里无法复现（Win10 1909, Chrome 78, 79, 80 都有）。下载按钮的实现是采用[这个回答](https://stackoverflow.com/a/3665147/5958455)里的方案，按理说兼容性应该没问题。实在不行的话这两个我刚生成的文件先拿去用吧。

- [pac-20200210-ipdeny.txt](https://github.com/iBug/pac/files/4179757/pac-20200210-ipdeny.txt)
- [pac-20200210-17mon.txt](https://github.com/iBug/pac/files/4179758/pac-20200210-17mon.txt)

**Comment by junmin** [comment]
@iBug 

谢谢，兼容性没有问题，我改一下代码里面的 proxy 变量就可以了。
使用了，反应速度好快，比shadowsocksX-NG自带的pac快多了，赞

我后面尝试debug一下看看能不能找出问题。

**Comment by junmin** [comment]
是btoa函数的问题，output变量里可能有些不是ascii的字符（但我没看出来）
btoa 函数写成下面这样就没有问题了。

`btoa(unescape(encodeURIComponent(output)))`

Unicode strings
In most browsers, calling btoa() on a Unicode string will cause an InvalidCharacterError exception.

One option is to escape any extended characters so that the string you actually encode is an ASCII representation of the original. 


https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#Unicode_Strings

**Comment by iBug** [comment]
我觉得没道理啊，整个代码都是可打印的 ASCII 字符。不过你这个建议我测试一下，没问题的话可以采纳，谢谢支持

**Comment by moneyyes** [comment]
我也有同样问题，症状是页面假死（只有那个页面的tab假死，别的tab正常，并不是整个chrome死掉），CPU风扇开始猛吹。期间会提示一次该页面无响应，选择继续等待后过一会会自动弹出pac.txt的下载页面

不过作者搞了个单独下pac的分支，也没问题了，谢谢作者

**Comment by iBug** [comment]
这个问题我后来研究出来了。一开始的做法是生成 pac 之后全部显示出来，由于内容超过 6000 行，给**浏览器渲染**带来了巨大的压力，导致页面卡住，所以我后来改成了不显示全部内容，把行数最多的 `var CHINA = []` 里面都省略掉了，结果确实好了很多，这个问题应该不再存在了。

虽然我现在更想把网页生成器直接 deprecate 掉了：<https://github.com/iBug/pac/issues/2#issuecomment-462220411>
